set_property IOSTANDARD LVCMOS33 [get_ports d128]
set_property IOSTANDARD LVCMOS33 [get_ports d192]
set_property IOSTANDARD LVCMOS33 [get_ports d256]
set_property IOSTANDARD LVCMOS33 [get_ports e128]
set_property IOSTANDARD LVCMOS33 [get_ports e192]
set_property IOSTANDARD LVCMOS33 [get_ports e256]
set_property IOSTANDARD LVCMOS33 [get_ports enable]

set_property PACKAGE_PIN M14 [get_ports e128]
set_property PACKAGE_PIN M15 [get_ports d128]
set_property PACKAGE_PIN G14 [get_ports e256]
set_property PACKAGE_PIN D18 [get_ports d256]
set_property PACKAGE_PIN G15 [get_ports enable]
set_property PACKAGE_PIN V15 [get_ports e192]
set_property PACKAGE_PIN W15 [get_ports d192]
